// This file is automatically generated. Do not modify it manually.

package main

var manifest = struct {
	ID      string
	Version string
}{
	ID:      "com.mattermost.custom-attributes",
	Version: "1.3.0",
}
